# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
dataset_list:
  -
    data_dir: 'F:\Datasets\Structured3D'
    out_dir: 'F:\Datasets\Structured3D'
    data_type: 'Structured3DDataGen'
    process_pipelines:
      -
        assemble_name: 'assemble_far_view'
        label_type: 'structured3d_living_11'
        room_types: [ 'living room' ]
        room_size: [ 9.6, 9.6 ]
        room_height: 4.8
        room_stride: 0.3
        render_cfg: 'Render-Structured3D-Living.yaml'
